print("Vamos calcular a distância entre dois pontos do plano cartesiano, sendo eles: p(x1,y1) e Q(x2,y2)")
x1=float(input("Digite o valor de x1:"))
y1=float(input("Digite o valor de y1:"))
x2=float(input("Digite o valor de x2:"))
y2=float(input("Digite o valor de y2:"))
d= (((x2-x1)**2)+((y2-y1)**2))**(1/2)
print("A distância entre os dois pontos é igual a:", d)